serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  enabled: true

  defaults:
    labels:
      release: prometheus
    interval: 30s
    scrapeTimeout: 30s
    module: http_2xx

  # make sure to use kubernetes serive names as target names
  targets:
    - name: prometheus
      url: http://prometheus.io
      labels:
        release: prometheus
    - name: nodejs-client-service
      url: http://nodejs-client-service.default.svc.cluster.local
      labels:
        release: prometheus
    - name: sla-manager-service
      url: http://sla-manager-service.default.svc.cluster.local
      labels:
        release: prometheus


config:
  modules:
    http_2xx:
      prober: http
      http:
        preferred_ip_protocol: "ip4"
