apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-client-deploy
  labels:
    app: nodejs-client-app
  annotations:
spec:
  selector:
    matchLabels:
      app: nodejs-client-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template: # Config for a Pod
    metadata:
      labels:
        app: nodejs-client-app
    spec:   # Blueprint for a Pod
      containers:
      - name: nodejs-client-app
        image: jxnasw/nodejs-client:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000   # Match targetPort of Service
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"