apiVersion: v1
kind: Service
metadata:
  name: sla-manager-frontend-service
  labels:
    app: sla-manager-frontend-app
    monitoring: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
spec:
  selector:
    app: sla-manager-frontend-app
  type: NodePort
  # ports:
  #   - port: 80
  #     targetPort: 80
  #     protocol: TCP
  #     nodePort: 31000
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000